# Generated by Django 4.1.4 on 2024-08-10 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 8, 10, 6, 42, 27, 818915, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
