# Generated by Django 4.1.4 on 2024-08-10 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_notes_created_at_notes_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='note',
            field=models.TextField(default=datetime.datetime(2024, 8, 10, 6, 46, 28, 70150, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
