# Generated by Django 4.1.4 on 2024-08-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_student_delete_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='genger',
            new_name='gender',
        ),
    ]
